---
title: "Differences in CO2 emissions between countries on different basis"
author:
- familyname: 
  othernames: 
  address: 
  email: 
  qualifications:
- familyname: 
  othernames: 
  address: 
  email: 
  qualifications:
- familyname: Gao
  othernames: Gui
  address: Monash University
  email: ggao0005@student.monash.edu
  qualifications:  Student
- familyname:
  othernames:
  address:
  email:  
  correspondingauthor: true
  qualifications: 
department: Our consultancy \newline add names &\newline add names
organization: 
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      comment = NA,
                      cache = TRUE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}

# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(tinytex)
library(rgdal)
library(sf)
library(gganimate)
```

# Analysis

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# read data
daily_caloric_supply <- read_csv("Data/daily-caloric-supply-derived-from-carbohydrates-protein-and-fat.csv")
dietary_compositions <- read_csv("Data/dietary-compositions-by-commodity-group.csv")
overweight_or_obese <- read_csv("Data/share-of-adult-men-overweight-or-obese-vs-daily-supply-of-calories.csv")
```


```{r}
# data wrangling
daily_caloric_supply <- daily_caloric_supply %>%
  rename_all(str_remove, pattern = "\\(FAO.+\\)") %>%
  select(-Code)

dietary_compositions <- dietary_compositions %>%
  rename_all(str_remove, pattern = "\\(FAO.+\\)") %>%
  select(-Code)
```


```{r}
# Area Plot
dietary_compositions %>%
  filter(Entity == "Australia") %>%
  pivot_longer(cols = -c(Entity, Year),
               names_to = "Variable",
               values_to = "Value") %>%
  ggplot(aes(x = Year,
             y = Value,
             fill = Variable)) +
  geom_area(color = "white") +
  scale_fill_viridis_d() +
  labs(y = "Kilocalories per Person per Day",
       title = "Kilocalories per Person per Day in Australia") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom',
        text = element_text(size = 8))

figure1 <- dietary_compositions %>% 
  filter(Entity == 'Australia') %>% 
  pivot_longer(cols = -c(Entity,Year),
               names_to = 'Variable',
               values_to = 'Value') %>% 
  ggplot(aes(x = Year, y = Value, fill = Variable)) +
  geom_area(color = 'white') +
  scale_fill_viridis_d() +
  labs(y = 'Kilocalories per Person per Day',
       title = 'Kilocalories per Person per Day in Australia') +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom',
        text = element_text(size = 8)) +
  transition_reveal(Year)

figure1
animate(figure1,
        res = 300,
        width = 2000,
        height = 1125,
        renderer = gifski_renderer())
anim_save("figure1.gif")
```


```{r}

```




